build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
formats: all
python:
   install:
   - requirements: doc/src/requirements.txt
sphinx:
   configuration: doc/user/conf.py
   fail_on_warning: true
version: 2
