build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    pre_create_environment:
      - rake prepare:doc
formats: all
python:
   install:
   - requirements: doc/src/requirements.txt
sphinx:
   configuration: doc/user/conf.py
   fail_on_warning: true
submodules:
  include: all
  recursive: true
version: 2
